In [8]:
import pandas as pd
df=pd.read_csv("fifa_players.csv")

In [9]:
df.head()

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,long_shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle
0,L. Messi,Lionel Andrés Messi Cuccittini,6/24/1987,31,170.18,72.1,"CF,RW,ST",Argentina,94,94,...,94,48,22,94,94,75,96,33,28,26
1,C. Eriksen,Christian Dannemann Eriksen,2/14/1992,27,154.94,76.2,"CAM,RM,CM",Denmark,88,89,...,89,46,56,84,91,67,88,59,57,22
2,P. Pogba,Paul Pogba,3/15/1993,25,190.50,83.9,"CM,CAM",France,88,91,...,82,78,64,82,88,82,87,63,67,67
3,L. Insigne,Lorenzo Insigne,6/4/1991,27,162.56,59.0,"LW,ST",Italy,88,88,...,84,34,26,83,87,61,83,51,24,22
4,K. Koulibaly,Kalidou Koulibaly,6/20/1991,27,187.96,88.9,CB,Senegal,88,91,...,15,87,88,24,49,33,80,91,88,87

In [10]:
df.tail()

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,long_shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle
17949,R. McKenzie,Rory McKenzie,10/7/1993,25,175.26,74.8,"RM,CAM,CM",Scotland,67,70,...,54,69,41,60,64,63,56,40,20,18
17950,M. Sipľak,Michal Sipľak,2/2/1996,23,182.88,79.8,LB,Slovakia,59,67,...,22,62,55,42,39,32,52,53,64,60
17951,J. Bekkema,Jan Bekkema,4/9/1996,22,185.42,89.8,GK,Netherlands,59,67,...,9,27,10,5,25,16,47,9,12,13
17952,A. Al Yami,Abdulrahman Al Yami,6/19/1997,21,175.26,64.9,"ST,LM",Saudi Arabia,59,71,...,58,38,15,54,52,50,53,16,18,17
17953,Júnior Brumado,José Francisco dos Santos Júnior,5/15/1999,19,190.50,79.8,ST,Brazil,59,75,...,53,67,20,53,49,52,45,23,31,21

In [11]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 17954
Columns: 51

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17954 entries, 0 to 17953
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   name                           17954 non-null  object
 1   full_name                      17954 non-null  object
 2   birth_date                     17954 non-null  object
 3   age                            17954 non-null  int64
 4   height_cm                      17954 non-null  float64
 5   weight_kgs                     17954 non-null  float64
 6   positions                      17954 non-null  object
 7   nationality                    17954 non-null  object
 8   overall_rating                 17954 non-null  int64
 9   potential                      17954 non-null  int64
 10  value_euro                     17699 non-null  float64
 11  wage_euro                      17708 non-null  float64
 12  preferred_foot                 17954 non-null  object
 13  international_reputation(1-5)  17954 non-null  int64
 14  weak_foot(1-5)                 17954 non-null  int64
 15  skill_moves(1-5)               17954 non-null  int64
 16  body_type                      17954 non-null  object
 17  release_clause_euro            16117 non-null  float64
 18  national_team                  857 non-null    object
 19  national_rating                857 non-null    float64
 20  national_team_position         857 non-null    object
 21  national_jersey_number         857 non-null    float64
 22  crossing                       17954 non-null  int64
 23  finishing                      17954 non-null  int64
 24  heading_accuracy               17954 non-null  int64
 25  short_passing                  17954 non-null  int64
 26  volleys                        17954 non-null  int64
 27  dribbling                      17954 non-null  int64
 28  curve                          17954 non-null  int64
 29  freekick_accuracy              17954 non-null  int64
 30  long_passing                   17954 non-null  int64
 31  ball_control                   17954 non-null  int64
 32  acceleration                   17954 non-null  int64
 33  sprint_speed                   17954 non-null  int64
 34  agility                        17954 non-null  int64
 35  reactions                      17954 non-null  int64
 36  balance                        17954 non-null  int64
 37  shot_power                     17954 non-null  int64
 38  jumping                        17954 non-null  int64
 39  stamina                        17954 non-null  int64
 40  strength                       17954 non-null  int64
 41  long_shots                     17954 non-null  int64
 42  aggression                     17954 non-null  int64
 43  interceptions                  17954 non-null  int64
 44  positioning                    17954 non-null  int64
 45  vision                         17954 non-null  int64
 46  penalties                      17954 non-null  int64
 47  composure                      17954 non-null  int64
 48  marking                        17954 non-null  int64
 49  standing_tackle                17954 non-null  int64
 50  sliding_tackle                 17954 non-null  int64
dtypes: float64(7), int64(35), object(9)
memory usage: 7.0+ MB

In [13]:
print("Columns in Dataset:\n")
print(df.columns.tolist())

Columns in Dataset:

['name', 'full_name', 'birth_date', 'age', 'height_cm', 'weight_kgs', 'positions', 'nationality', 'overall_rating', 'potential', 'value_euro', 'wage_euro', 'preferred_foot', 'international_reputation(1-5)', 'weak_foot(1-5)', 'skill_moves(1-5)', 'body_type', 'release_clause_euro', 'national_team', 'national_rating', 'national_team_position', 'national_jersey_number', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'dribbling', 'curve', 'freekick_accuracy', 'long_passing', 'ball_control', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'marking', 'standing_tackle', 'sliding_tackle']

In [14]:
df.sample(5, random_state=42)

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,long_shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle
9834,S. Davies,Steven Davies,12/29/1987,31,185.42,73.0,ST,England,64,64,...,64,69,38,66,61,66,67,31,44,34
5815,L. Ashby-Hammond,Luca Ashby-Hammond,3/25/2001,17,185.42,76.2,GK,England,56,76,...,9,14,8,4,32,41,38,9,14,10
4093,G. McEachran,George McEachran,8/30/2000,18,172.72,64.9,"CAM,CM",England,59,81,...,32,49,35,53,64,50,63,38,55,52
7476,Y. Goke,郷家 友太,6/10/1999,19,182.88,73.9,"CM,RM,LM",Japan,61,73,...,47,44,49,58,59,47,58,55,45,32
16455,Edercinho Sepa,Rodrigo Éder Serpa Conceição,2/29/1988,31,152.40,76.2,"CDM,CM",Brazil,74,74,...,77,66,66,70,63,70,69,81,76,68

In [15]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,17954.0,2.556545e+01,4.705708e+00,17.0,22.00,25.00,29.00,4.600000e+01
height_cm,17954.0,1.749469e+02,1.402945e+01,152.4,154.94,175.26,185.42,2.057400e+02
weight_kgs,17954.0,7.530105e+01,7.083684e+00,49.9,69.90,74.80,79.80,1.102000e+02
overall_rating,17954.0,6.624017e+01,6.963730e+00,47.0,62.00,66.00,71.00,9.400000e+01
potential,17954.0,7.143093e+01,6.131339e+00,48.0,67.00,71.00,75.00,9.500000e+01
value_euro,17699.0,2.479280e+06,5.687014e+06,10000.0,325000.00,700000.00,2100000.00,1.105000e+08
wage_euro,17708.0,9.902135e+03,2.199559e+04,1000.0,1000.00,3000.00,9000.00,5.650000e+05
international_reputation(1-5),17954.0,1.111674e+00,3.921679e-01,1.0,1.00,1.00,1.00,5.000000e+00
weak_foot(1-5),17954.0,2.945695e+00,6.636915e-01,1.0,3.00,3.00,3.00,5.000000e+00
skill_moves(1-5),17954.0,2.361034e+00,7.632226e-01,1.0,2.00,2.00,3.00,5.000000e+00
release_clause_euro,16117.0,4.622522e+06,1.129077e+07,13000.0,525000.00,1200000.00,3500000.00,2.265000e+08
national_rating,857.0,7.634189e+01,4.786667e+00,63.0,73.00,75.00,81.00,8.500000e+01
national_jersey_number,857.0,1.245624e+01,8.098157e+00,1.0,6.00,12.00,18.00,9.900000e+01
crossing,17954.0,4.969767e+01,1.848331e+01,5.0,38.00,54.00,64.00,9.300000e+01
finishing,17954.0,4.535825e+01,1.964079e+01,2.0,30.00,49.00,62.00,9.500000e+01
heading_accuracy,17954.0,5.214821e+01,1.752182e+01,4.0,44.00,56.00,64.00,9.400000e+01
short_passing,17954.0,5.856606e+01,1.486318e+01,7.0,53.00,62.00,68.00,9.300000e+01
volleys,17954.0,4.275521e+01,1.780294e+01,3.0,30.00,44.00,57.00,9.000000e+01
dribbling,17954.0,5.527899e+01,1.909188e+01,4.0,49.00,61.00,68.00,9.700000e+01
curve,17954.0,4.710115e+01,1.853662e+01,6.0,34.00,49.00,62.00,9.400000e+01
freekick_accuracy,17954.0,4.268809e+01,1.756563e+01,3.0,30.00,41.00,56.00,9.400000e+01
long_passing,17954.0,5.266743e+01,1.542155e+01,9.0,43.00,56.00,64.00,9.300000e+01
ball_control,17954.0,5.822391e+01,1.687572e+01,5.0,54.00,63.00,69.00,9.600000e+01
acceleration,17954.0,6.469622e+01,1.500134e+01,12.0,57.00,67.00,75.00,9.700000e+01
sprint_speed,17954.0,6.480350e+01,1.472275e+01,12.0,58.00,67.00,75.00,9.600000e+01
agility,17954.0,6.337746e+01,1.480695e+01,11.0,55.00,66.00,74.00,9.600000e+01
reactions,17954.0,6.182188e+01,9.075675e+00,24.0,56.00,62.00,68.00,9.600000e+01
balance,17954.0,6.387006e+01,1.417404e+01,16.0,56.00,66.00,74.00,9.600000e+01
shot_power,17954.0,5.531987e+01,1.735130e+01,2.0,45.00,59.00,68.00,9.500000e+01
jumping,17954.0,6.495522e+01,1.170571e+01,15.0,58.00,66.00,73.00,9.500000e+01
stamina,17954.0,6.313384e+01,1.591755e+01,12.0,56.00,66.00,74.00,9.700000e+01
strength,17954.0,6.515885e+01,1.253595e+01,20.0,58.00,66.00,74.00,9.700000e+01
long_shots,17954.0,4.685246e+01,1.942934e+01,3.0,32.00,51.00,62.00,9.400000e+01
aggression,17954.0,5.581653e+01,1.739405e+01,11.0,44.00,59.00,69.00,9.500000e+01
interceptions,17954.0,4.665796e+01,2.075465e+01,3.0,26.00,52.00,64.00,9.200000e+01
positioning,17954.0,4.985730e+01,1.969431e+01,2.0,38.00,55.00,64.00,9.500000e+01
vision,17954.0,5.340626e+01,1.415604e+01,10.0,44.00,55.00,64.00,9.400000e+01
penalties,17954.0,4.835730e+01,1.581084e+01,5.0,38.00,49.00,60.00,9.200000e+01
composure,17954.0,5.868018e+01,1.162554e+01,12.0,51.00,60.00,67.00,9.600000e+01
marking,17954.0,4.716286e+01,2.003735e+01,3.0,30.00,52.50,64.00,9.400000e+01
standing_tackle,17954.0,4.773304e+01,2.167497e+01,2.0,27.00,55.00,66.00,9.300000e+01
sliding_tackle,17954.0,4.570592e+01,2.128581e+01,3.0,24.00,52.00,64.00,9.000000e+01

In [16]:
df.describe(include='object').T

                        count unique           top   freq
name                    17954  16995  J. Rodríguez      8
full_name               17954  17898  Adama Traoré      3
birth_date              17954   6156     2/29/1992    115
positions               17954    890            CB   2243
nationality             17954    160       England   1658
preferred_foot          17954      2         Right  13781
body_type               17954     10        Normal  10393
national_team             857    103      Scotland     23
national_team_position    857     29           SUB    389

In [17]:
missing=pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})
missing.sort_values("Missing Values",ascending=False)

                               Missing Values  Percentage
national_jersey_number                  17097   95.226690
national_team_position                  17097   95.226690
national_rating                         17097   95.226690
national_team                           17097   95.226690
release_clause_euro                      1837   10.231703
value_euro                                255    1.420296
wage_euro                                 246    1.370168
name                                        0    0.000000
shot_power                                  0    0.000000
ball_control                                0    0.000000
acceleration                                0    0.000000
sprint_speed                                0    0.000000
agility                                     0    0.000000
reactions                                   0    0.000000
balance                                     0    0.000000
stamina                                     0    0.000000
jumping                                     0    0.000000
freekick_accuracy                           0    0.000000
strength                                    0    0.000000
long_shots                                  0    0.000000
aggression                                  0    0.000000
interceptions                               0    0.000000
positioning                                 0    0.000000
vision                                      0    0.000000
penalties                                   0    0.000000
composure                                   0    0.000000
marking                                     0    0.000000
standing_tackle                             0    0.000000
long_passing                                0    0.000000
short_passing                               0    0.000000
curve                                       0    0.000000
preferred_foot                              0    0.000000
birth_date                                  0    0.000000
age                                         0    0.000000
height_cm                                   0    0.000000
weight_kgs                                  0    0.000000
positions                                   0    0.000000
nationality                                 0    0.000000
overall_rating                              0    0.000000
potential                                   0    0.000000
international_reputation(1-5)               0    0.000000
dribbling                                   0    0.000000
weak_foot(1-5)                              0    0.000000
skill_moves(1-5)                            0    0.000000
body_type                                   0    0.000000
crossing                                    0    0.000000
finishing                                   0    0.000000
heading_accuracy                            0    0.000000
full_name                                   0    0.000000
volleys                                     0    0.000000
sliding_tackle                              0    0.000000

In [18]:
duplicates=df.duplicated().sum()
print(f"Duplicate Rows: {duplicates}")

Duplicate Rows: 0

In [19]:
for column in df.columns:
    print(f"{column}: {df[column].nunique()} unique values")

name: 16995 unique values
full_name: 17898 unique values
birth_date: 6156 unique values
age: 29 unique values
height_cm: 20 unique values
weight_kgs: 57 unique values
positions: 890 unique values
nationality: 160 unique values
overall_rating: 47 unique values
potential: 47 unique values
value_euro: 211 unique values
wage_euro: 138 unique values
preferred_foot: 2 unique values
international_reputation(1-5): 5 unique values
weak_foot(1-5): 5 unique values
skill_moves(1-5): 5 unique values
body_type: 10 unique values
release_clause_euro: 1248 unique values
national_team: 103 unique values
national_rating: 22 unique values
national_team_position: 29 unique values
national_jersey_number: 38 unique values
crossing: 89 unique values
finishing: 94 unique values
heading_accuracy: 91 unique values
short_passing: 85 unique values
volleys: 88 unique values
dribbling: 94 unique values
curve: 89 unique values
freekick_accuracy: 92 unique values
long_passing: 84 unique values
ball_control: 90 unique values
acceleration: 86 unique values
sprint_speed: 85 unique values
agility: 82 unique values
reactions: 68 unique values
balance: 81 unique values
shot_power: 91 unique values
jumping: 74 unique values
stamina: 86 unique values
strength: 74 unique values
long_shots: 92 unique values
aggression: 85 unique values
interceptions: 88 unique values
positioning: 94 unique values
vision: 85 unique values
penalties: 87 unique values
composure: 83 unique values
marking: 91 unique values
standing_tackle: 89 unique values
sliding_tackle: 87 unique values

In [20]:
df.dtypes

name                              object
full_name                         object
birth_date                        object
age                                int64
height_cm                        float64
weight_kgs                       float64
positions                         object
nationality                       object
overall_rating                     int64
potential                          int64
value_euro                       float64
wage_euro                        float64
preferred_foot                    object
international_reputation(1-5)      int64
weak_foot(1-5)                     int64
skill_moves(1-5)                   int64
body_type                         object
release_clause_euro              float64
national_team                     object
national_rating                  float64
national_team_position            object
national_jersey_number           float64
crossing                           int64
finishing                          int64
heading_accuracy                   int64
short_passing                      int64
volleys                            int64
dribbling                          int64
curve                              int64
freekick_accuracy                  int64
long_passing                       int64
ball_control                       int64
acceleration                       int64
sprint_speed                       int64
agility                            int64
reactions                          int64
balance                            int64
shot_power                         int64
jumping                            int64
stamina                            int64
strength                           int64
long_shots                         int64
aggression                         int64
interceptions                      int64
positioning                        int64
vision                             int64
penalties                          int64
composure                          int64
marking                            int64
standing_tackle                    int64
sliding_tackle                     int64
dtype: object

In [ ]:
plt.